### ISSUE TITLE
每一部分的最大值这里感觉存在问题

### ISSUE THREAD

**Issue by kid1412621** [beyondfengyu/SnowFlake#7]
`private static final long MAX_SEQUENCE = -1L ^ (-1L << SEQUENCE_BIT)`

这里假设 SEQUENCE_BIT = 3；结果是 7。
但不应该是 2^3 = 8 吗？
为什么不直接是：
`private static final long MAX_SEQUENCE = 1L << SEQUENCE_BIT`
不知道有什么其它考量吗？

**Comment by MissThee** [comment]
8是1000，二进制站4位。
7是111，二进制站3位

**Comment by kid1412621** [comment]
> 8 是 1000，二进制站 4 位。
> 7 是 111，二进制站 3 位

感谢，把 0 搞漏了。
