### ISSUE TITLE
多线程情况下有ID值重复

### ISSUE THREAD

**Issue by henry0249** [beyondfengyu/SnowFlake#8]
public static void main(String[] args) {
        SnowFlake snowFlake = new SnowFlake(2, 3);

        for (int i = 0; i < 8000; i++) {
            Thread thread = new Thread() {
                public void run() {
                    // 测试情况下会有重复id出现
                    ystem.out.println(snowFlake.nextId());
                }
            };
            thread.start();
        }

    }

**Comment by cw760** [comment]
test your code, can't reproduce.
